### ISSUE TITLE
Can no longer save game

### ISSUE THREAD

**Issue by ValhalQoholic** [JohnnyonFlame/handheld-iortcw#2]
I'm playing RTCW on an RK3326 handheld.  I'm over halfway through the game and it stopped saving the game.  I hit "save" in the menu, and no new save file shows up under "load".  Any idea how I could fix that?

**Comment by JohnnyonFlame** [comment]
That's incredibly weird, I wonder if you ran out of space.

**Comment by ValhalQoholic** [comment]
OMG that was it.  I had to ssh into my device.  I deleted a bunch of old save files and that allowed me to save again!
